[workspace]
members = [
	".", "ole-pcg",
#	"rb-okvs"
]
[workspace.dependencies]
aes = "0.8"
rand = "0.8.5"
aes-prng = "0.2"
dmpf = {path = "."}
ole-pcg = {path = "ole-pcg"}
rand_chacha = "0.3.1"
itertools = "0.13"
fpe = "0.6.1"

# rb-okvs = {path = "rb-okvs"}


[package]
name = "dmpf"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1"
aes = {workspace = true}
rand = {workspace = true}
aes-prng = {workspace = true}
rand_chacha = {workspace = true}
itertools = {workspace = true}
fpe = {workspace = true}

# rb-okvs = {workspace = true}

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "dpf"
harness = false

[[bench]]
name = "batch_code"
harness = false

[[bench]]
name = "prg"
harness = false

[[bench]]
name = "okvs"
harness = false

[[bench]]
name = "fpe"
harness = false

[[bin]]
name = "estimate_okvs"



[build]
rustflags = ["-C", "target-cpu=native"]
