[package]
name = "dmpf_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
aes = "0.8"
once_cell = "1"

[dev-dependencies]
aes-prng = "0.2"